### ISSUE TITLE
Adicionar alguns tipos de identificadores?

### ISSUE THREAD

**Issue by matheusfelipeog** [Coding-in-community/materiais#1]
Talvez adicionar alguns identificadores ajudem na busca pelo conteúdo ideal para determinados membros da comunidade?

Por exemplo, adicionar um identificador:
- de nível do conteúdo (Basíco, Intermediário, Avançado);
- se é vídeo ou texto;
- se está em inglês ou português e etc...

**Comment by carlos3g** [comment]
Seria interessante. Que estrutura você sugere?

Que tal uma tabela para cada tecnologia, com campos de titulo (com link), nível, preço, idioma e ano (se disponível)?

**Comment by matheusfelipeog** [comment]
Acho que manter uma estrutura tabular por tecnologia é uma boa ideia.

Ficaria mais ou menos assim:

| Conteúdo | Nível | Idioma | Tipo (Vídeo ou Texto) | Ano | Preço |
|---|---|---|---|---|---|
| 1 | 1 | 1 | 1 | 1 | 1 |
| 2 | 2 | 2 | 2 | 2 | 2 |

Acha que realmente é útil informar o valor de determinado conteúdo aqui? Talvez informar apenas se é gratuíto ou pago seria suficiente?

**Comment by carlos3g** [comment]
Realmente é melhor infomar apenas se é gratuito ou pago, até porque preço é algo variável.

No caso da label de tipo, que tal colocar apenas "Tipo", invés de "Tipo (Vídeo ou Texto)", e no ínicio do README colocar uma sessão de observações com um item explicando quais os tipos de conteúdos disponíveis (EX: livro, jogo educativo, post...)? Assim economiza espaço horizontal em telas menores

| Conteúdo | Nível | Idioma | Tipo | Ano | Acesso |
|---|---|---|---|---|---|
| [1](#) | Avançado | PT | Livro | 2014 | Pago |
| [2](#) | Gratuito | EN | Vídeo | 2021 | Gratuito |

De qualquer forma acredito que a mudança já pode ser implementada. Você pode fazer isso?

**Comment by matheusfelipeog** [comment]
> No caso da label de tipo, que tal colocar apenas "Tipo", invés de "Tipo (Vídeo ou Texto)", e no ínicio do README colocar uma sessão de observações com um item explicando quais os tipos de conteúdos disponíveis (EX: livro, jogo educativo, post...)? Assim economiza espaço horizontal em telas menores

Ótima observação, vou seguir assim

> De qualquer forma acredito que a mudança já pode ser implementada. Você pode fazer isso?

Perfeito, vou trabalhar nisso e envio para sua revisão
